version: "3.9"

services:
  db:
    image: postgres:14
    container_name: ab0-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./AB0-1-back
      dockerfile: Dockerfile
    container_name: ab0-backend
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-app_db}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET:-changeme}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - ./AB0-1-back:/app
    ports:
      - "3001:3001"
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3001"]

  frontend:
    build:
      context: ./AB0-1-front
      dockerfile: Dockerfile
    container_name: ab0-frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  db_data:
