version: "3.9"

services:
  db:
    image: postgres:14
    container_name: ab0-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./AB0-1-back
      dockerfile: Dockerfile
    container_name: ab0-backend
    depends_on:
      - db
    env_file:
      - ./AB0-1-back/.env.secrets
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      CORS_ORIGINS: "https://avaliasolar.com.br"
    volumes:
      - ./AB0-1-back:/app
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./AB0-1-front
      dockerfile: Dockerfile
    container_name: ab0-frontend
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "https://api.avaliasolar.com.br/api/v1"
    ports:
      - "3000:3000"
    command: ["node", "server.js"]

volumes:
  db_data:
