default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'ab0_development' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

test:
  <<: *default
  database: ab0_test
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
