name: CI/CD Deploy

on:
  push:
    branches:
      - main   # dispara no push para main
      - master-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # LOGIN GITHUB CONTAINER REGISTRY
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push Images
      - name: Fix Registry Names and Deploy Images
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          chmod +x ./script/fix-registry-names.sh
          ./script/fix-registry-names.sh

      # DEPLOY NA VM
      - name: Check SSH Connection
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          VM_KEY: ${{ secrets.VM_KEY }}
        run: |
          chmod +x ./script/check_ssh_connection.sh
          if [[ -z "$VM_HOST" ]]; then
            echo "Error: VM_HOST secret is not set"
            exit 1
          fi
          if [[ -z "$VM_USER" ]]; then
            echo "Error: VM_USER secret is not set"
            exit 1
          fi
          ./script/check_ssh_connection.sh "$VM_HOST" "$VM_USER" "$VM_KEY"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          port: 22
          command_timeout: 15m
          timeout: 15m
          script_stop: true
          script: |
            set -e

            echo "==> Atualizando projeto em produção"
            mkdir -p ~/ab0-app && cd ~/ab0-app

            echo "==> Criando/atualizando docker-compose.yml"
            cat > docker-compose.yml <<'EOF'
            version: "3.9"

            services:
              db:
                image: postgres:14
                container_name: ab0-postgres
                restart: always
                environment:
                  POSTGRES_USER: ${POSTGRES_USER}
                  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                  POSTGRES_DB: ${POSTGRES_DB}
                volumes:
                  - db_data:/var/lib/postgresql/data
                ports:
                  - "5432:5432"

              backend:
                image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ab0-1-backend:latest
                container_name: ab0-backend
                depends_on:
                  - db
                environment:
                  RAILS_ENV: production
                  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
                  RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
                  JWT_SECRET: ${JWT_SECRET}
                  POSTGRES_HOST: db
                  POSTGRES_USER: ${POSTGRES_USER}
                  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                  POSTGRES_DB: ${POSTGRES_DB}
                  CORS_ORIGINS: https://www.avaliasolar.com.br,https://api.avaliasolar.com.br
                ports:
                  - "3001:3001"

              frontend:
                image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ab0-frontend:latest
                container_name: ab0-frontend
                depends_on:
                  - backend
                environment:
                  NODE_ENV: production
                  NEXT_PUBLIC_API_URL: https://api.avaliasolar.com.br
                  NEXT_PUBLIC_SITE_URL: https://www.avaliasolar.com.br
                ports:
                  - "3000:3000"

            volumes:
              db_data:
            EOF

            echo "==> Criando arquivo .env"
            cat > .env <<EOF
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            NEXT_PUBLIC_API_URL=https://api.avaliasolar.com.br
            NEXT_PUBLIC_SITE_URL=https://www.avaliasolar.com.br
            EOF

            echo "==> Subindo containers atualizados"
            docker compose pull
            docker compose down
            docker compose up -d --remove-orphans

            echo "==> Limpando imagens antigas não usadas"
            docker image prune -af
