name: Deploy Backend

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env.production
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.production
          echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> .env.production
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env.production
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.production
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.production
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.production
          cat .env.production

      - name: Build Docker image
        run: |
          docker build -t ab0-backend:${{ github.sha }} .

      - name: Save Docker image as tar
        run: |
          docker save ab0-backend:${{ github.sha }} -o ab0-backend.tar
          chmod 644 ab0-backend.tar

      - name: Copy docker image to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ab0-backend.tar
          target: ~/images

      - name: Load and Run docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Load new image
            docker load -i ~/images/ab0-backend.tar

            # Stop and remove old container
            docker rm -f ab0-backend || true

            # Create network if it doesn't exist
            docker network create ab0-network || true

            # Run new container with environment variables
            docker run -d \
              --name ab0-backend \
              --network ab0-network \
              -e RAILS_ENV=production \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e RAILS_MASTER_KEY="${{ secrets.RAILS_MASTER_KEY }}" \
              -e POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}" \
              -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
              -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
              -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
              -p 3001:3001 \
              ab0-backend:${{ github.sha }}

            # Wait for container to start
            sleep 10

            # Debug information
            echo "Container Status:"
            docker ps | grep ab0-backend

            echo "Container Logs:"
            docker logs --tail=50 ab0-backend

            echo "Network Check:"
            docker network inspect ab0-network | grep ab0-backend || true

            echo "Port Check:"
            ss -tulpn | grep 3001 || true
