name: Deploy Backend

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env.production
        run: |
          cat > .env.production << EOL
          RAILS_ENV=production
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          CORS_ORIGINS=http://64.225.59.107:3000
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOL

      - name: Build Docker image
        run: |
          docker build -t ab0-backend:${{ github.sha }} .

      - name: Save Docker image as tar
        run: |
          mkdir -p /tmp/docker-images
          docker save ab0-backend:${{ github.sha }} -o /tmp/docker-images/ab0-backend.tar
          chmod 644 /tmp/docker-images/ab0-backend.tar

      - name: Copy docker image to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: ab0-backend.tar
          target: ~/images

      - name: Load and Run docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Load new image
            docker load -i ~/images/ab0-backend.tar

            # Stop and remove old container
            docker rm -f ab0-backend || true

            # Create network if it doesn't exist
            docker network create ab0-network || true

            # Run new container with environment variables (using single quotes)
            docker run -d \
              --name ab0-backend \
              --network ab0-network \
              -e RAILS_ENV=production \
              -e "DATABASE_URL=${DATABASE_URL}" \
              -e "RAILS_MASTER_KEY=${RAILS_MASTER_KEY}" \
              -e "POSTGRES_HOST=${POSTGRES_HOST}" \
              -e "POSTGRES_USER=${POSTGRES_USER}" \
              -e "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" \
              -e "POSTGRES_DB=${POSTGRES_DB}" \
              -e "CORS_ORIGINS=http://64.225.59.107:3000" \
              -e "JWT_SECRET=${JWT_SECRET}" \
              -p 3001:3001 \
              ab0-backend:${{ github.sha }}

            # Debug information
            echo "Container Status:"
            docker ps | grep ab0-backend

            echo "Container Logs:"
            docker logs --tail=50 ab0-backend

            echo "Network Check:"
            docker network inspect ab0-network | grep ab0-backend || true

            echo "Port Check:"
            ss -tulpn | grep 3001 || true
